version: "3.9"
services:
  app:
    build: .
    container_name: student-grades-app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: student-grades-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grades
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/student_grade_management.sql:/docker-entrypoint-initdb.d/student_grade_management.sql

volumes:
  db_data:
